name : Continous deployment

on:
  push:
    branches:
      - abhinai
jobs:
  get_keys:
    runs-on: ubuntu-latest
    name: deployment into aws
    steps:
      - uses: hashicorp/setup-terraform@v2
      - name: get_aws_keys
        run: |
          mkdir ~/.aws/
          cd ~/.aws/
          echo "[default]" >> credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> credentials 
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> credentials 
          cat credentials
          echo "[default]" >> config
          cat config
      - name: private key
        run: |
          echo "${{ secrets.AWS_KEY_PAIR }}" > kalyan.pem
          sudo chmod 400 kalyan.pem
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - run: |
          ls
          terraform init
      - run: terraform validate
      - run: terraform plan  